discord:
  token: ${DC_TOKEN}
  application-id: ${DC_APP_ID}
  guild-id: ${DC_GID:-1}
quarkus:
  log:
    category:
      org.inquest:
        level: DEBUG
    file:
      enable: true
      path: logs/isac.log
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c] (%t) %s%e%n"
  mongodb:
    connection-string: ${MONGO_DB_URL:mongodb://localhost:27017}
    database: isac
    connect-timeout: 10s
  http:
    cors:
      ~: true
      origins:
        - https://inquestur.com
        - https://www.inquestur.com
        - /http://localhost:[0-9]+/
      methods: GET