discord:
  token: ${DC_TOKEN}
  application-id: ${DC_APP_ID}
  guild-id: ${DC_GID:-1}
  channel-id: ${DC_CID:-1}
quarkus:
  banner:
    path: BANNER
  log:
    category:
      org.inquest:
        level: DEBUG
    file:
      enable: true
      path: logs/isac.log
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c] (%t) %s%e%n"
  mongodb:
    connection-string: ${MONGO_DB_URL:mongodb://localhost:27017}
    database: isac
    connect-timeout: 10s
  http:
    port: ${HTTP_PORT:8080}
    insecure-requests: ${HTTP_REDIRECT:enabled}
    ssl:
      certificate:
        files: ${CERT_FILES}
        key-files: ${CERT_KEYS}
    ssl-port: ${HTTPS_PORT:8443}
    cors:
      ~: true
      origins: ${CORS_ORIGINS:/.*//localhost:.*/}
      access-control-allow-credentials: true