name: Push to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean compile build
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./src/main/docker/Dockerfile.jvm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/i.s.a.c:latest
          context: ./
